### PR TITLE
Fix argument handling in echobot.

### PR DESCRIPTION
**Pull request by yurivict**
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxins/8)

### CODE REVIEW

**Comment by yurivict** [comment]
I don't understand why does it need any rebase, because the base of my commit was the last commit.
```
Merge attempt failed
Base branch requires signed commits. Rebase merges cannot be automatically signed by GitHub.
```

**Comment by nurupo** [comment]
:lgtm_strong:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/toktok/toxins/8#-:-L8V4y7gENbmdLnhgyYf:b-jbsf8z)*

**Comment by nurupo** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/toktok/toxins/8)*

**Comment by yurivict** [comment]
This repository is misconfigured. Merge commit is disabled, and rebased commit can't be done because of the gpg signature requirement.

**Comment by nurupo** [comment]
No, it's properly configured. It's probably a protection against people merging PRs from the web interface, which you are not supposed to do. Remember when you have done so in https://github.com/TokTok/toxins/pull/3 and iphy has asked you to use the command line in the future?

**Pull request merged**
