### PR TITLE
Fix argument handling in echobot.

### PR DESCRIPTION
**Pull request by yurivict**
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxins/7)

### CODE REVIEW

**Comment by iphydf** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxins/7#-:-L8UfbeUdTE1w3ISO-4J:b-jbsf8z)*

**Comment by iphydf** [comment]
Why close it?

**Comment by yurivict** [comment]
Sorry, e-mail mismatch in my gpg signature. I've recreated it. -)

**Comment by nurupo** [comment]
You could have simply modified the commit in this PR, no need to create a new PR just for that.

**Comment by yurivict** [comment]
I didn't know that it is possible to change e-mail. Never did that. -)

**Comment by nurupo** [comment]
You can change literally anything: name, email, commit name, commit contents, order of commits, remove commits from anywhere and add new commits anywhere, etc.

**Comment by yurivict** [comment]
Thanks @nurupo , it's good to know!

**Pull request closed without merging**
