### PR TITLE
Add echobot to toxins.

### PR DESCRIPTION
**Pull request by iphydf**
From https://wiki.tox.chat/developers/client_examples/echo_bot.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxins/3)

### CODE REVIEW

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxins/3#-:-L5uSZiGxjrmqvECbYxo:b-jbsf8z)*

**Comment by nurupo** [comment]
Just the simple, most cross-platform version (there are two version on the wiki)? Alright, looks good.

Btw, although zero-one was the one who created that wiki page, it was written by me. I think I gisted it and he made a page out of my gist.

**Comment by nurupo** [comment]
Aha, found it. It was moved from other wiki page:

```
#tox-dev_20151103.log: <nurupo> added an example for introducing new developers to toxcore c api https://wiki.tox.chat/developers/echo_bot_example
#tox-dev_20151103.log: <nurupo> wiki looks horrible in comparison to gist :\ https://gist.github.com/nurupo/8c6c1d455b39b0830668
...
#tox-dev_20151103.log: <Jfreegman> nurupo: nice, can i tweet it or is it not done?
...
#tox-dev_20151103.log: <nurupo> Jfreegman: proof reading first would be great
#tox-dev_20151103.log: <Jfreegman> doing that right now
...
#tox-dev_20151103.log: <zero-one> nurupo: does "echo_bot_example" really belong in the root of the developers namespace
...
#tox-dev_20151103.log: <nurupo> zero-one: it's aimed at developers
...
#tox-dev_20151103.log: <zero-one> but it belongs in a folder
#tox-dev_20151103.log: <nurupo> just fix it then
...
#tox-dev_20151103.log: <nurupo> zero-one: you want to create examples directory?
#tox-dev_20151103.log: <nurupo> or you actually meant something else
#tox-dev_20151103.log: <zero-one> nurupo: i'll just do it
#tox-dev_20151103.log: <nurupo> ok
...
#tox-dev_20151103.log: <zero-one> Jfreegman: what are you doing with the echo_bot doc
#tox-dev_20151103.log: <zero-one> i'm about to delete it
#tox-dev_20151103.log: <Jfreegman> what why
#tox-dev_20151103.log: <Jfreegman> im editing the grammar
#tox-dev_20151103.log: <zero-one> i'm moving it
#tox-dev_20151103.log: <zero-one> edit this: https://wiki.tox.chat/developers/client_examples/echo_bot
#tox-dev_20151103.log: <Jfreegman> go for it
```

Anyway, I'm only mentioning this in case you want to note authorship or do something with the license, stuff like that. Though now that I think about it, the wiki license should be very permissive, so you probably don't need any of that, so you can disregard this all. Some much text and for nothing :P

**Comment by yurivict** [comment]
Can this be merged?

**Comment by iphydf** [comment]
Yes, it can be merged, but please use the command line, not the github interface.

**Pull request merged**
