### PR TITLE
Use pkg-config for toxcore cflags and ldflags.

### PR DESCRIPTION
**Pull request by yurivict**
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxins/5)

### CODE REVIEW

**Comment by iphydf** [comment]
Ok, but why? Does the build not work for you without this? Note that this will make it fail for people who don't have pkg-config.

**Comment by yurivict** [comment]
https://github.com/TokTok/toxins/issues/4

It doesn't work with the latest version toxcore-0.1.11_1,1

**Comment by iphydf** [comment]
Understood. Ok, this repo needs 0.2.0, which we'll release soon.

**Comment by yurivict** [comment]
Will wait for the next release.

**Pull request closed without merging**
